[package]
name = "draw-layout"
version = "0.0.1"
entrypoint = "lib/lib.typ"
authors = ["Qujihan <https://github.com/qujihan>"]
license = "MIT"
description = "generating formatted pictures that can be used by programmers in their documentation or presentations."
repository = "https://github.com/qujihan/typst-drawformat"
keywords = ["draw-layout", "layout", "header", "memory", "map", "register"]
compiler = "0.12.0"
exclude = [
    "examples/**",
    "doc/**",
    "**.png",
    "**.pdf",
    "makefile",
    "LICENCE",
    "README.**",
    "CONTRIBUTE.**",
]
